create table user(
    id bigint generated by default as identity(start with 1) not null,
    name varchar(64),
    username varchar(255) not null unique,
    password varchar(255) not null,
    email varchar(50),
    salt varchar(64),
    status varchar(32),
    primary key(id)
);

create table role(
    id bigint generated by default as identity(start with 1) not null,
    name varchar(255) not null unique,
    permissions varchar(255),
    primary key(id)
);

create table user_role(
    user_id bigint not null,
    role_id bigint not null,
    primary key(user_id,role_id)
);